CREATE DATABASE SSHManager;
USE SSHManager;

CREATE TABLE IF NOT EXISTS Projects (
ProjectID INT PRIMARY KEY AUTO_INCREMENT,
ProjectName VARCHAR(30) NOT NULL,
CompanyName VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Instances (
InstanceID INT PRIMARY KEY AUTO_INCREMENT,
ARN VARCHAR(128) NOT NULL,
ipAddress VARCHAR(15) NOT NULL,
SSHKey VARCHAR(300) NOT NULL,
ProjectID INT NOT NULL,
CONSTRAINT fk_instances_projects FOREIGN KEY (ProjectID) REFERENCES Projects (ProjectID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Users (
UserID INT PRIMARY KEY AUTO_INCREMENT,
UserName VARCHAR(50) NOT NULL,
UserPass VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Instances_Users (
InstanceID INT NOT NULL,
UserID INT NOT NULL,
PRIMARY KEY (InstanceID, UserID),
CONSTRAINT fk_iu_instances FOREIGN KEY (InstanceID) REFERENCES Instances (InstanceID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_iu_users FOREIGN KEY (UserID) REFERENCES Users (UserID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Projects_Users (
ProjectID INT NOT NULL,
UserID INT NOT NULL,
PRIMARY KEY (ProjectID, UserID),
CONSTRAINT fk_pu_projects FOREIGN KEY (ProjectID) REFERENCES Projects (ProjectID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_pu_users FOREIGN KEY (UserID) REFERENCES Users (UserID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SHOW TABLES;
